### ISSUE TITLE
ipv4.ddnspod.com返回ipv6地址

### ISSUE THREAD

**Issue by myunco** [ddnspod/ddnspod.github.io#1]
> http(s)://ipv4.ddnspod.com   Only ipv4 for Global

由于ipv4.ddnspod.com可被ipv6解析，导致在ipv6可用的情况下会返回ipv6地址，不再是Only ipv4
能否使ipv4.ddnspod.com仅能使用ipv4访问？

**Comment by myunco** [comment]
> http(s)://ipv4.ddnspod.com   Only ipv4 for Global

由于ipv4.ddnspod.com可被ipv6解析，导致在ipv6可用的情况下会返回ipv6地址，不再是Only ipv4
能否使ipv4.ddnspod.com仅能使用ipv4访问？

**Comment by ddnspod** [comment]
经测试，只有部分地区的部分宽带用户会返回AAAA解析，相关问题已反馈给cdn服务商，待本地dns缓存刷新后即不再返回ipv6地址

**Comment by myunco** [comment]
多谢处理，问题已解决。
